CREATE TABLE IF NOT EXISTS stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app varchar NOT NULL,
  uri varchar NOT NULL,
  ip varchar(15) NOT NULL,
  timestamp timestamp NOT NULL
);